### ISSUE TITLE
Wrong uploader path in "Add an image uploader"

### ISSUE THREAD

**Issue by C0casio45** [AdobeDocs/commerce-frontend-core#97]
### Expected Behaviour

define Magento_PageBuilder/js/uploader

### Actual Behaviour

define Magento_PageBuilder/js/content-type/uploader

### Reproduce Scenario (including but not limited to)

follow the steps at [dev docs : add an image uploader](https://developer.adobe.com/commerce/frontend-core/page-builder/content-types/customize/add-image-uploader/)

**Comment by C0casio45** [comment]
Also, not sure if I am doing wrong but while patching the uploader path, I got error on using the tutorial

```
Uncaught (in promise) TypeError: Unable to process binding "template: function(){return { name:preview.template,data:preview,afterRender:function(){ preview.dispatchAfterRenderEvent.apply(preview,arguments);}} }"
Message: Unable to process binding "style: function(){return Object.assign({},data.main.style(),!data.desktop_image.attributes().src ?{}:{borderStyle:'none'}) }"
Message: Cannot read properties of undefined (reading 'attributes')
    at style (eval at createBindingsStringEvaluator (knockout.js:3221:28), <anonymous>:3:208)
    at evaluateValueAccessor (knockout.js:3494:28)
    at knockout.js:3671:44
    at update (style.js:33:62)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3745:45)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2331:115)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2288:41)
    at Function.evaluateImmediate (knockout.js:2253:40)
    at ko.computed.ko.dependentObservable (knockout.js:2085:40)
    at knockout.js:3743:40
```
